/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Swing */

#ifndef _Included_Swing
#define _Included_Swing
#ifdef __cplusplus
extern "C" {
#endif
#undef Swing_FOCUS_TRAVERSABLE_UNKNOWN
#define Swing_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef Swing_FOCUS_TRAVERSABLE_DEFAULT
#define Swing_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef Swing_FOCUS_TRAVERSABLE_SET
#define Swing_FOCUS_TRAVERSABLE_SET 2L
#undef Swing_TOP_ALIGNMENT
#define Swing_TOP_ALIGNMENT 0.0f
#undef Swing_CENTER_ALIGNMENT
#define Swing_CENTER_ALIGNMENT 0.5f
#undef Swing_BOTTOM_ALIGNMENT
#define Swing_BOTTOM_ALIGNMENT 1.0f
#undef Swing_LEFT_ALIGNMENT
#define Swing_LEFT_ALIGNMENT 0.0f
#undef Swing_RIGHT_ALIGNMENT
#define Swing_RIGHT_ALIGNMENT 1.0f
#undef Swing_serialVersionUID
#define Swing_serialVersionUID -7644114512714619750i64
#undef Swing_serialVersionUID
#define Swing_serialVersionUID 4613797578919906343i64
#undef Swing_INCLUDE_SELF
#define Swing_INCLUDE_SELF 1L
#undef Swing_SEARCH_HEAVYWEIGHTS
#define Swing_SEARCH_HEAVYWEIGHTS 1L
#undef Swing_OPENED
#define Swing_OPENED 1L
#undef Swing_serialVersionUID
#define Swing_serialVersionUID 4497834738069338734i64
#undef Swing_DEFAULT_CURSOR
#define Swing_DEFAULT_CURSOR 0L
#undef Swing_CROSSHAIR_CURSOR
#define Swing_CROSSHAIR_CURSOR 1L
#undef Swing_TEXT_CURSOR
#define Swing_TEXT_CURSOR 2L
#undef Swing_WAIT_CURSOR
#define Swing_WAIT_CURSOR 3L
#undef Swing_SW_RESIZE_CURSOR
#define Swing_SW_RESIZE_CURSOR 4L
#undef Swing_SE_RESIZE_CURSOR
#define Swing_SE_RESIZE_CURSOR 5L
#undef Swing_NW_RESIZE_CURSOR
#define Swing_NW_RESIZE_CURSOR 6L
#undef Swing_NE_RESIZE_CURSOR
#define Swing_NE_RESIZE_CURSOR 7L
#undef Swing_N_RESIZE_CURSOR
#define Swing_N_RESIZE_CURSOR 8L
#undef Swing_S_RESIZE_CURSOR
#define Swing_S_RESIZE_CURSOR 9L
#undef Swing_W_RESIZE_CURSOR
#define Swing_W_RESIZE_CURSOR 10L
#undef Swing_E_RESIZE_CURSOR
#define Swing_E_RESIZE_CURSOR 11L
#undef Swing_HAND_CURSOR
#define Swing_HAND_CURSOR 12L
#undef Swing_MOVE_CURSOR
#define Swing_MOVE_CURSOR 13L
#undef Swing_NORMAL
#define Swing_NORMAL 0L
#undef Swing_ICONIFIED
#define Swing_ICONIFIED 1L
#undef Swing_MAXIMIZED_HORIZ
#define Swing_MAXIMIZED_HORIZ 2L
#undef Swing_MAXIMIZED_VERT
#define Swing_MAXIMIZED_VERT 4L
#undef Swing_MAXIMIZED_BOTH
#define Swing_MAXIMIZED_BOTH 6L
#undef Swing_serialVersionUID
#define Swing_serialVersionUID 2673458971256075116i64
#undef Swing_EXIT_ON_CLOSE
#define Swing_EXIT_ON_CLOSE 3L
/*
 * Class:     Swing
 * Method:    calculateMean
 * Signature: ([I)D
 */
JNIEXPORT jdouble JNICALL Java_Swing_calculateMean
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     Swing
 * Method:    calculateSTDDev
 * Signature: ([I)D
 */
JNIEXPORT jdouble JNICALL Java_Swing_calculateSTDDev
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
